### ISSUE TITLE
cannot access '/timeline' url

### ISSUE THREAD

**Issue by kaliif** [maykinmedia/django-timeline-logger#13]
The app is working, entries get logged to database but http://localhost:8000/timeline, as described in docs keeps giving me 404. I've tried http://localhost:8000/<myappname>/timeline and http://localhost:8000/admin/timeline but still nothing. Thoughts?

**Comment by sergei-maertens** [comment]
Did you include the urls in your main urlconfig?

```python
urlpattersn = [
    ...
    url(r'^timeine/', include('timeline_logger.urls),
    ...
]
```

Can you point me at the part of the documentation that mentions this url, this may be a documentation issue :)

**Comment by blfpd** [comment]
@sergei-maertens Indeed, the urlpatterns snippet is missing: [docs/usage.rst#L68](https://github.com/maykinmedia/django-timeline-logger/blob/develop/docs/usage.rst#L68)

**Comment by kaliif** [comment]
You mean path instead of url, right? All my other patterns begin with path.
But no, that doesn't fix my issue, still 404.
Entirely possible it's just some step missing from the docs.

**Comment by kaliif** [comment]
Shoot, noticed a typo. Working now, thanks.
