### ISSUE TITLE
not a single screenshot

### ISSUE THREAD

**Issue by felipelerena** [maykinmedia/django-timeline-logger#31]
I can't find a screenshot on how this actually looks on the whole internet.

**Comment by sergei-maertens** [comment]
The default template (https://github.com/maykinmedia/django-timeline-logger/blob/master/timeline_logger/templates/timeline_logger/timelinelog_list.html) is just a minimal working example without any styling. Users of the package should provide their own template, markup and CSS, so you're limited only by your own creativity :smile:

**Comment by felipelerena** [comment]
yeah, I'm using something else because of that. thanks

**Comment by sergei-maertens** [comment]
glad to hear you found a better alternative, good luck on your project!
